### ISSUE TITLE
Req'd packages -- perhaps different in Ubuntu 14.10?

### ISSUE THREAD

**Issue by dwblair** [bgamari/skeleton-geda-project#1]
Allo! Awesomesauce.

geda-netlist and pcb weren't in the repositories, seemingly --

pcb could be installed as pcb-gtk;
but geda-netlist is MIA ...

**Comment by dwblair** [comment]
Oh, maybe it's geda-gnetlist?

**Comment by bgamari** [comment]
Indeed it is. Fixed in `README`.
